version: "3.3"

services:
  api:
    build: 
      context: .
      args:
        - ENV=development
    entrypoint: [ "/start-reload.sh" ]
    ports:
      - 127.0.0.1:8000:80
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  postgres_data:
